server.port=8888
spring.application.name=config-server

# Relative path to the config-repo folder
spring.cloud.config.server.git.uri=file://${user.dir}/config-repo
spring.cloud.config.server.git.default-label=main

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
